/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 *
 * http://rtsys.informatik.uni-kiel.de/kieler
 *
 * Copyright 2026 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */

import type { NotificationType } from 'vscode-messenger-common'

// Messages between the extension and the simulation controls inside the diagram preview webview.
// This file is compiled into both bundles, so it must stay free of vscode and DOM imports.

export type SimulationRole = 'input' | 'output' | 'local'

export interface SimulationVariableState {
    id: string
    label: string
    role: SimulationRole
    categories: string[]
    /** Values per tick within the sent window; the last entry is the current tick. */
    history: unknown[]
    /** Inputs only: the value the server will read at the next tick. */
    next?: unknown
    /** Inputs only: `next` was changed by the user and the server has not seen it yet. */
    pending: boolean
    /** Guards, tick counters and other symbols generated by the compiler. */
    internal: boolean
}

export type SimulationPhase = 'idle' | 'starting' | 'running' | 'stopping'

/** A compiler stage shown in the diagram instead of the source model. */
export interface ShownStageState {
    name: string
    /** Position among all stages, 1-based, and their count. */
    position: number
    count: number
}

/** A breakpoint as shown in the preview; `state` for entry breakpoints, `expression` for conditions. */
export interface BreakpointState {
    id: string
    kind: 'state' | 'condition'
    state?: string
    expression?: string
    enabled: boolean
    /** Rejected by the server: the reason, shown next to the breakpoint. */
    error?: string
    /** Accepted with a note, e.g. an ambiguous state name. */
    note?: string
}

export interface WatchState {
    id: string
    expression: string
    value?: unknown
    error?: string
}

/** The breakpoint the simulation last stopped at. */
export interface BreakpointPause {
    id: string
    kind: string
    label: string
    step: number
}

/** A state of the simulated model, as listed by the server for the breakpoint picker. */
export interface ModelStateInfo {
    name: string
    /** Dotted path from the root, unique within the model. */
    qualified: string
    initial?: boolean
    current?: boolean
}

export interface SimulationDebugState {
    breakpoints: BreakpointState[]
    /** Nested states of the model, for picking an entry breakpoint; empty when the server could not list them. */
    states: ModelStateInfo[]
    watches: WatchState[]
    /** Set on the tick a breakpoint fired; cleared by the next tick. */
    paused?: BreakpointPause
    /** A rewind is possible: there is an earlier tick to go back to. */
    canStepBack: boolean
    /** The server is stepping on its own towards the next breakpoint. */
    runningToBreakpoint: boolean
    /** A loaded trace drives the inputs, so ticks cannot be replayed. */
    traceLoaded: boolean
}

export interface SimulationViewState {
    phase: SimulationPhase
    canStart: boolean
    playing: boolean
    tick: number
    /** Tick number of `history[0]`; earlier ticks are dropped to bound the message size. */
    firstTick: number
    stepDelay: number
    showInternal: boolean
    /** URI and file name of the model shown in this preview. */
    modelUri?: string
    model?: string
    variables: SimulationVariableState[]
    error?: string
    /** The model was edited after the running simulation was built; Restart rebuilds it. */
    stale?: boolean
    /** Set while the diagram shows a compiler stage rather than the model. */
    stage?: ShownStageState
    /** The model is an SCCharts file on disk, so C or Java can be generated from it. */
    canGenerate?: boolean
    /** Breakpoints, watches and rewind availability of the running simulation. */
    debug?: SimulationDebugState
}

export type SimulationViewCommand =
    | { kind: 'requestState' }
    | { kind: 'start' }
    | { kind: 'step' }
    | { kind: 'play' }
    | { kind: 'pause' }
    | { kind: 'stop' }
    | { kind: 'restart' }
    | { kind: 'saveTrace' }
    | { kind: 'loadTrace' }
    | { kind: 'setInput'; id: string; value: unknown }
    | { kind: 'setStepDelay'; delay: number }
    | { kind: 'setShowInternal'; enabled: boolean }
    | { kind: 'rebuild' }
    | { kind: 'showModel' }
    | { kind: 'showStage' }
    | { kind: 'generateCode' }
    | { kind: 'addBreakpoint'; state?: string; expression?: string }
    | { kind: 'removeBreakpoint'; id: string }
    | { kind: 'toggleBreakpoint'; id: string; enabled: boolean }
    | { kind: 'addWatch'; expression: string }
    | { kind: 'removeWatch'; id: string }
    | { kind: 'stepBack'; toStep?: number }
    | { kind: 'runToBreakpoint' }

export const simulationStateNotification: NotificationType<SimulationViewState> = {
    method: 'keith/simulation/viewState',
}

/** The preview URI captured when a control was used, before the panel can switch files. */
export type SimulationViewRequest = SimulationViewCommand & { modelUri?: string }

export const simulationCommandNotification: NotificationType<SimulationViewRequest> = {
    method: 'keith/simulation/viewCommand',
}

/** How many ticks of history are sent to the view. */
export const HISTORY_WINDOW = 200
