/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 *
 * http://rtsys.informatik.uni-kiel.de/kieler
 *
 * Copyright 2026 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */

import type { NotificationType } from 'vscode-messenger-common'

// Messages between the extension and the simulation controls inside the diagram preview webview.
// This file is compiled into both bundles, so it must stay free of vscode and DOM imports.

export type SimulationRole = 'input' | 'output' | 'local'

export interface SimulationVariableState {
    id: string
    label: string
    role: SimulationRole
    categories: string[]
    /** Values per tick within the sent window; the last entry is the current tick. */
    history: unknown[]
    /** Inputs only: the value the server will read at the next tick. */
    next?: unknown
    /** Inputs only: `next` was changed by the user and the server has not seen it yet. */
    pending: boolean
    /** Guards, tick counters and other symbols generated by the compiler. */
    internal: boolean
}

export type SimulationPhase = 'idle' | 'starting' | 'running' | 'stopping'

export interface SimulationViewState {
    phase: SimulationPhase
    canStart: boolean
    playing: boolean
    tick: number
    /** Tick number of `history[0]`; earlier ticks are dropped to bound the message size. */
    firstTick: number
    stepDelay: number
    showInternal: boolean
    /** URI and file name of the model shown in this preview. */
    modelUri?: string
    model?: string
    variables: SimulationVariableState[]
    error?: string
}

export type SimulationViewCommand =
    | { kind: 'requestState' }
    | { kind: 'start' }
    | { kind: 'step' }
    | { kind: 'play' }
    | { kind: 'pause' }
    | { kind: 'stop' }
    | { kind: 'restart' }
    | { kind: 'saveTrace' }
    | { kind: 'loadTrace' }
    | { kind: 'openExternal' }
    | { kind: 'setInput'; id: string; value: unknown }
    | { kind: 'setStepDelay'; delay: number }
    | { kind: 'setShowInternal'; enabled: boolean }

export const simulationStateNotification: NotificationType<SimulationViewState> = {
    method: 'keith/simulation/viewState',
}

/** The preview URI captured when a control was used, before the panel can switch files. */
export type SimulationViewRequest = SimulationViewCommand & { modelUri?: string }

export const simulationCommandNotification: NotificationType<SimulationViewRequest> = {
    method: 'keith/simulation/viewCommand',
}

/** How many ticks of history are sent to the view. */
export const HISTORY_WINDOW = 200
