# CI workflow used for code quality checks and to ensure that a PR can be built.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Run eslint and test and build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x
            - run: yarn

            - name: Restore server runtime
              uses: actions/cache@v4
              with:
                  path: |
                      keith-vscode/server/kieler-language-server.jar
                      keith-vscode/server/jetty10
                  key: server-${{ hashFiles('keith-vscode/server/manifest.json') }}
            - run: yarn workspace keith-vscode fetch-server

            - run: yarn workspace keith-vscode test
            - run: yarn workspace keith-vscode test:server
            - run: yarn tsc --noEmit -p keith-vscode/tsconfig.json
            - run: yarn tsc --noEmit -p keith-vscode/tsconfig.webview.json
            - run: yarn package
            - run: yarn lint

            - name: Attach SCCharts Lab extension
              uses: actions/upload-artifact@v4
              with:
                  name: sccharts-lab-vsix
                  path: keith-vscode/sccharts-lab.vsix
                  if-no-files-found: error
